// This file is auto-generated by @hey-api/openapi-ts

export const ApprovePendingRequestSchema = {
    properties: {
        user_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'User Id'
        },
        create_user: {
            type: 'boolean',
            title: 'Create User',
            default: false
        }
    },
    type: 'object',
    title: 'ApprovePendingRequest',
    description: `Approve a pending GitHub login.

Exactly one of \`\`user_id\`\` or \`\`create_user\`\` must be provided.`
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const Body_workshop_badges_upload_workshop_badge_imageSchema = {
    properties: {
        file: {
            type: 'string',
            format: 'binary',
            title: 'File'
        }
    },
    type: 'object',
    required: ['file'],
    title: 'Body_workshop-badges-upload_workshop_badge_image'
} as const;

export const BridgeResponseSchema = {
    properties: {
        status: {
            type: 'string',
            enum: ['signed_in', 'pending_approval'],
            title: 'Status'
        },
        access_token: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Access Token'
        },
        token_type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Token Type'
        },
        pending_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Pending Id'
        }
    },
    type: 'object',
    required: ['status'],
    title: 'BridgeResponse',
    description: `Discriminated response from the GitHub bridge endpoint.

- \`\`status="signed_in"\`\` -> \`\`access_token\`\` and \`\`token_type\`\` are set,
  \`\`pending_id\`\` is null.
- \`\`status="pending_approval"\`\` -> \`\`pending_id\`\` is set, token fields null.`
} as const;

export const GitHubBridgeRequestSchema = {
    properties: {
        bridge_token: {
            type: 'string',
            title: 'Bridge Token'
        }
    },
    type: 'object',
    required: ['bridge_token'],
    title: 'GitHubBridgeRequest'
} as const;

export const GithubInstallationAccessibleRepositoriesPublicSchema = {
    properties: {
        installation_id: {
            type: 'integer',
            title: 'Installation Id'
        },
        repository_selection: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Repository Selection'
        },
        full_names: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Full Names'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['installation_id', 'full_names', 'count'],
    title: 'GithubInstallationAccessibleRepositoriesPublic'
} as const;

export const GithubInstallationListItemPublicSchema = {
    properties: {
        installation_id: {
            type: 'integer',
            title: 'Installation Id'
        },
        account_login: {
            type: 'string',
            title: 'Account Login'
        },
        account_type: {
            type: 'string',
            title: 'Account Type'
        },
        repository_selection: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Repository Selection'
        },
        app_slug: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'App Slug'
        },
        suspended: {
            type: 'boolean',
            title: 'Suspended'
        },
        entitled_repositories_count: {
            type: 'integer',
            title: 'Entitled Repositories Count'
        },
        entitled_repositories: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Entitled Repositories'
        },
        installation_settings_url: {
            type: 'string',
            title: 'Installation Settings Url'
        }
    },
    type: 'object',
    required: ['installation_id', 'account_login', 'account_type', 'suspended', 'entitled_repositories_count', 'entitled_repositories', 'installation_settings_url'],
    title: 'GithubInstallationListItemPublic'
} as const;

export const GithubInstallationListPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/GithubInstallationListItemPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        },
        install_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Install Url'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'GithubInstallationListPublic'
} as const;

export const GithubInstallationRefreshBodySchema = {
    properties: {
        include_repositories: {
            type: 'boolean',
            title: 'Include Repositories',
            default: false
        }
    },
    type: 'object',
    title: 'GithubInstallationRefreshBody'
} as const;

export const GithubInstallationRefreshPublicSchema = {
    properties: {
        installations_refreshed: {
            type: 'integer',
            title: 'Installations Refreshed'
        },
        installations_created: {
            type: 'integer',
            title: 'Installations Created'
        },
        installations_updated: {
            type: 'integer',
            title: 'Installations Updated'
        },
        repositories_refreshed: {
            type: 'integer',
            title: 'Repositories Refreshed'
        }
    },
    type: 'object',
    required: ['installations_refreshed', 'installations_created', 'installations_updated', 'repositories_refreshed'],
    title: 'GithubInstallationRefreshPublic'
} as const;

export const GithubInstallationRepositoriesRefreshPublicSchema = {
    properties: {
        installation_id: {
            type: 'integer',
            title: 'Installation Id'
        },
        repository_selection: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Repository Selection'
        },
        repositories_total: {
            type: 'integer',
            title: 'Repositories Total'
        },
        added: {
            type: 'integer',
            title: 'Added'
        },
        removed: {
            type: 'integer',
            title: 'Removed'
        },
        unchanged: {
            type: 'integer',
            title: 'Unchanged'
        }
    },
    type: 'object',
    required: ['installation_id', 'repositories_total', 'added', 'removed', 'unchanged'],
    title: 'GithubInstallationRepositoriesRefreshPublic'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const ItemCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'ItemCreate'
} as const;

export const ItemPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['title', 'id', 'owner_id'],
    title: 'ItemPublic'
} as const;

export const ItemUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'ItemUpdate'
} as const;

export const ItemsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ItemPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ItemsPublic'
} as const;

export const LessonRepoGithubSyncBodySchema = {
    properties: {
        full_name: {
            type: 'string',
            maxLength: 255,
            title: 'Full Name'
        },
        installation_id: {
            type: 'integer',
            exclusiveMinimum: 0,
            title: 'Installation Id'
        }
    },
    type: 'object',
    required: ['full_name', 'installation_id'],
    title: 'LessonRepoGithubSyncBody'
} as const;

export const LessonRepoGithubSyncPublicSchema = {
    properties: {
        lesson_repo_id: {
            type: 'string',
            format: 'uuid',
            title: 'Lesson Repo Id'
        },
        lessons_synced: {
            type: 'integer',
            title: 'Lessons Synced'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        health: {
            type: 'string',
            title: 'Health'
        },
        default_branch: {
            type: 'string',
            title: 'Default Branch'
        }
    },
    type: 'object',
    required: ['lesson_repo_id', 'lessons_synced', 'full_name', 'health', 'default_branch'],
    title: 'LessonRepoGithubSyncPublic'
} as const;

export const LessonRepoListItemPublicSchema = {
    properties: {
        lesson_repo_id: {
            type: 'string',
            format: 'uuid',
            title: 'Lesson Repo Id'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        default_branch: {
            type: 'string',
            title: 'Default Branch'
        },
        health: {
            type: 'string',
            title: 'Health'
        },
        github_installation_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Github Installation Id'
        },
        last_synced_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Synced At'
        },
        lesson_count: {
            type: 'integer',
            title: 'Lesson Count'
        },
        part_count: {
            type: 'integer',
            title: 'Part Count'
        },
        manifest_count: {
            type: 'integer',
            title: 'Manifest Count'
        },
        last_manifest_synced_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Manifest Synced At'
        }
    },
    type: 'object',
    required: ['lesson_repo_id', 'full_name', 'default_branch', 'health', 'lesson_count', 'part_count', 'manifest_count'],
    title: 'LessonRepoListItemPublic'
} as const;

export const LessonRepoListPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/LessonRepoListItemPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'LessonRepoListPublic'
} as const;

export const LessonRepoPreviewLessonPublicSchema = {
    properties: {
        lesson_id: {
            type: 'string',
            format: 'uuid',
            title: 'Lesson Id'
        },
        lesson_slug: {
            type: 'string',
            title: 'Lesson Slug'
        },
        lesson_title: {
            type: 'string',
            title: 'Lesson Title'
        },
        parts: {
            items: {
                '$ref': '#/components/schemas/LessonRepoPreviewPartPublic'
            },
            type: 'array',
            title: 'Parts'
        }
    },
    type: 'object',
    required: ['lesson_id', 'lesson_slug', 'lesson_title', 'parts'],
    title: 'LessonRepoPreviewLessonPublic'
} as const;

export const LessonRepoPreviewPartPublicSchema = {
    properties: {
        slug: {
            type: 'string',
            title: 'Slug'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        ordering: {
            type: 'integer',
            title: 'Ordering'
        },
        path: {
            type: 'string',
            title: 'Path'
        }
    },
    type: 'object',
    required: ['slug', 'title', 'ordering', 'path'],
    title: 'LessonRepoPreviewPartPublic'
} as const;

export const LessonRepoPreviewPublicSchema = {
    properties: {
        lesson_repo_id: {
            type: 'string',
            format: 'uuid',
            title: 'Lesson Repo Id'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        default_branch: {
            type: 'string',
            title: 'Default Branch'
        },
        health: {
            type: 'string',
            title: 'Health'
        },
        lessons: {
            items: {
                '$ref': '#/components/schemas/LessonRepoPreviewLessonPublic'
            },
            type: 'array',
            title: 'Lessons'
        }
    },
    type: 'object',
    required: ['lesson_repo_id', 'full_name', 'default_branch', 'health', 'lessons'],
    title: 'LessonRepoPreviewPublic'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const OAuthAccountPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        provider: {
            type: 'string',
            title: 'Provider'
        },
        provider_account_id: {
            type: 'string',
            title: 'Provider Account Id'
        },
        provider_login: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Provider Login'
        },
        avatar_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Avatar Url'
        },
        linked_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Linked At'
        }
    },
    type: 'object',
    required: ['id', 'user_id', 'provider', 'provider_account_id'],
    title: 'OAuthAccountPublic'
} as const;

export const PendingGitHubLoginPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        provider: {
            type: 'string',
            title: 'Provider'
        },
        provider_account_id: {
            type: 'string',
            title: 'Provider Account Id'
        },
        provider_login: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Provider Login'
        },
        email: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        avatar_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Avatar Url'
        },
        first_seen_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'First Seen At'
        },
        last_seen_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Seen At'
        },
        attempt_count: {
            type: 'integer',
            title: 'Attempt Count'
        }
    },
    type: 'object',
    required: ['id', 'provider', 'provider_account_id', 'attempt_count'],
    title: 'PendingGitHubLoginPublic'
} as const;

export const PendingGitHubLoginsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/PendingGitHubLoginPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'PendingGitHubLoginsPublic'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        },
        is_instructor: {
            type: 'boolean',
            title: 'Is Instructor',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const PrivateWorkshopE2ELiveSessionResponseSchema = {
    properties: {
        session_id: {
            type: 'string',
            format: 'uuid',
            title: 'Session Id'
        }
    },
    type: 'object',
    required: ['session_id'],
    title: 'PrivateWorkshopE2ELiveSessionResponse'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        is_instructor: {
            type: 'boolean',
            title: 'Is Instructor',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        is_instructor: {
            type: 'boolean',
            title: 'Is Instructor',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        is_instructor: {
            type: 'boolean',
            title: 'Is Instructor',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;

export const WorkshopBadgeDefinitionCreateSchema = {
    properties: {
        slug: {
            type: 'string',
            maxLength: 128,
            title: 'Slug'
        },
        title: {
            type: 'string',
            maxLength: 255,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1024
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        points: {
            type: 'integer',
            maximum: 1000,
            minimum: 0,
            title: 'Points',
            default: 1
        }
    },
    type: 'object',
    required: ['slug', 'title'],
    title: 'WorkshopBadgeDefinitionCreate'
} as const;

export const WorkshopBadgeDefinitionPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        slug: {
            type: 'string',
            title: 'Slug'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        points: {
            type: 'integer',
            title: 'Points'
        },
        lesson_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Lesson Id'
        },
        lesson_slug: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Lesson Slug'
        },
        lesson_title: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Lesson Title'
        },
        image_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image Url',
            description: 'Relative API path to uploaded image, or null to use UI default artwork.'
        }
    },
    type: 'object',
    required: ['id', 'slug', 'title', 'points'],
    title: 'WorkshopBadgeDefinitionPublic'
} as const;

export const WorkshopBadgeDefinitionsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/WorkshopBadgeDefinitionPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'WorkshopBadgeDefinitionsPublic'
} as const;

export const WorkshopBadgeGrantRequestSchema = {
    properties: {
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        badge_id: {
            type: 'string',
            format: 'uuid',
            title: 'Badge Id'
        }
    },
    type: 'object',
    required: ['user_id', 'badge_id'],
    title: 'WorkshopBadgeGrantRequest'
} as const;

export const WorkshopBadgeRevokeRequestSchema = {
    properties: {
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        badge_id: {
            type: 'string',
            format: 'uuid',
            title: 'Badge Id'
        },
        reason: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Reason'
        }
    },
    type: 'object',
    required: ['user_id', 'badge_id'],
    title: 'WorkshopBadgeRevokeRequest'
} as const;

export const WorkshopGlobalLeaderboardPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/WorkshopGlobalLeaderboardRowPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'WorkshopGlobalLeaderboardPublic'
} as const;

export const WorkshopGlobalLeaderboardRowPublicSchema = {
    properties: {
        rank: {
            type: 'integer',
            minimum: 1,
            title: 'Rank'
        },
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            type: 'string',
            title: 'Email'
        },
        avatar_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Avatar Url'
        },
        total_points: {
            type: 'integer',
            minimum: 0,
            title: 'Total Points'
        },
        badge_count: {
            type: 'integer',
            minimum: 0,
            title: 'Badge Count'
        }
    },
    type: 'object',
    required: ['rank', 'user_id', 'email', 'total_points', 'badge_count'],
    title: 'WorkshopGlobalLeaderboardRowPublic'
} as const;

export const WorkshopLessonPartBriefSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        ordering: {
            type: 'integer',
            title: 'Ordering'
        },
        slug: {
            type: 'string',
            title: 'Slug'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        estimated_minutes: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Estimated Minutes'
        },
        body_html: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Body Html'
        }
    },
    type: 'object',
    required: ['id', 'ordering', 'slug', 'title'],
    title: 'WorkshopLessonPartBrief',
    description: 'Lesson part metadata for workshop session screens (body omitted).'
} as const;

export const WorkshopLessonPrerequisiteAggregatePublicSchema = {
    properties: {
        prerequisite: {
            '$ref': '#/components/schemas/WorkshopLessonPrerequisitePublic'
        },
        roster_count: {
            type: 'integer',
            minimum: 0,
            title: 'Roster Count',
            description: 'Active roster trainee seats.'
        },
        completed_count: {
            type: 'integer',
            minimum: 0,
            title: 'Completed Count',
            description: 'Roster trainees with a completion row for this prerequisite.'
        }
    },
    type: 'object',
    required: ['prerequisite', 'roster_count', 'completed_count'],
    title: 'WorkshopLessonPrerequisiteAggregatePublic',
    description: 'Session roster completion counts per prerequisite definition (no per-user identity).'
} as const;

export const WorkshopLessonPrerequisiteAggregatesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/WorkshopLessonPrerequisiteAggregatePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'WorkshopLessonPrerequisiteAggregatesPublic'
} as const;

export const WorkshopLessonPrerequisiteCompleteSchema = {
    properties: {
        user_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'User Id'
        }
    },
    type: 'object',
    title: 'WorkshopLessonPrerequisiteComplete'
} as const;

export const WorkshopLessonPrerequisiteCreateSchema = {
    properties: {
        type: {
            type: 'string',
            maxLength: 32,
            title: 'Type',
            default: 'task'
        },
        title: {
            type: 'string',
            maxLength: 255,
            title: 'Title'
        },
        details: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1024
                },
                {
                    type: 'null'
                }
            ],
            title: 'Details'
        },
        url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1024
                },
                {
                    type: 'null'
                }
            ],
            title: 'Url'
        },
        ordering: {
            type: 'integer',
            minimum: 0,
            title: 'Ordering',
            default: 0
        },
        required_flag: {
            type: 'boolean',
            title: 'Required Flag',
            default: true
        }
    },
    type: 'object',
    required: ['title'],
    title: 'WorkshopLessonPrerequisiteCreate'
} as const;

export const WorkshopLessonPrerequisiteGapPublicSchema = {
    properties: {
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        email: {
            type: 'string',
            title: 'Email'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        incomplete_required_prerequisites: {
            items: {
                '$ref': '#/components/schemas/WorkshopLessonPrerequisitePublic'
            },
            type: 'array',
            title: 'Incomplete Required Prerequisites'
        }
    },
    type: 'object',
    required: ['user_id', 'email', 'incomplete_required_prerequisites'],
    title: 'WorkshopLessonPrerequisiteGapPublic',
    description: 'Trainee prerequisite gap for instructor cohort views (scoped to a workshop session roster).'
} as const;

export const WorkshopLessonPrerequisiteGapsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/WorkshopLessonPrerequisiteGapPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'WorkshopLessonPrerequisiteGapsPublic',
    description: 'Users on the session roster who still owe at least one *required* prerequisite.'
} as const;

export const WorkshopLessonPrerequisiteMyPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        lesson_id: {
            type: 'string',
            format: 'uuid',
            title: 'Lesson Id'
        },
        type: {
            type: 'string',
            title: 'Type'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        details: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Details'
        },
        url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Url'
        },
        ordering: {
            type: 'integer',
            title: 'Ordering'
        },
        required_flag: {
            type: 'boolean',
            title: 'Required Flag'
        },
        is_completed: {
            type: 'boolean',
            title: 'Is Completed'
        },
        completed_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Completed At'
        },
        source: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Source'
        }
    },
    type: 'object',
    required: ['id', 'lesson_id', 'type', 'title', 'ordering', 'required_flag', 'is_completed'],
    title: 'WorkshopLessonPrerequisiteMyPublic'
} as const;

export const WorkshopLessonPrerequisitePatchSchema = {
    properties: {
        type: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 32
                },
                {
                    type: 'null'
                }
            ],
            title: 'Type'
        },
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        details: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1024
                },
                {
                    type: 'null'
                }
            ],
            title: 'Details'
        },
        url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1024
                },
                {
                    type: 'null'
                }
            ],
            title: 'Url'
        },
        ordering: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ordering'
        },
        required_flag: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Required Flag'
        }
    },
    type: 'object',
    title: 'WorkshopLessonPrerequisitePatch'
} as const;

export const WorkshopLessonPrerequisitePublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        lesson_id: {
            type: 'string',
            format: 'uuid',
            title: 'Lesson Id'
        },
        type: {
            type: 'string',
            title: 'Type'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        details: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Details'
        },
        url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Url'
        },
        ordering: {
            type: 'integer',
            title: 'Ordering'
        },
        required_flag: {
            type: 'boolean',
            title: 'Required Flag'
        }
    },
    type: 'object',
    required: ['id', 'lesson_id', 'type', 'title', 'ordering', 'required_flag'],
    title: 'WorkshopLessonPrerequisitePublic'
} as const;

export const WorkshopLessonPrerequisitesMyPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/WorkshopLessonPrerequisiteMyPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'WorkshopLessonPrerequisitesMyPublic'
} as const;

export const WorkshopLessonPrerequisitesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/WorkshopLessonPrerequisitePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'WorkshopLessonPrerequisitesPublic'
} as const;

export const WorkshopLessonSummaryPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        slug: {
            type: 'string',
            title: 'Slug'
        },
        lesson_repo_health: {
            type: 'string',
            title: 'Lesson Repo Health',
            default: 'healthy'
        },
        lesson_repo_last_synced_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Lesson Repo Last Synced At'
        },
        lesson_content_available: {
            type: 'boolean',
            title: 'Lesson Content Available',
            default: true
        },
        lesson_content_issue: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Lesson Content Issue'
        }
    },
    type: 'object',
    required: ['id', 'title', 'slug'],
    title: 'WorkshopLessonSummaryPublic'
} as const;

export const WorkshopParticipantPatchSchema = {
    properties: {
        live_status: {
            anyOf: [
                {
                    type: 'string',
                    enum: ['busy', 'done']
                },
                {
                    type: 'null'
                }
            ],
            title: 'Live Status'
        },
        joined_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Joined At'
        },
        finished_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Finished At'
        }
    },
    type: 'object',
    title: 'WorkshopParticipantPatch',
    description: 'Instructor override fields for a participant seat.'
} as const;

export const WorkshopParticipantSelfPublicSchema = {
    properties: {
        invited_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Invited At'
        },
        joined_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Joined At'
        },
        finished_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Finished At'
        },
        live_status: {
            type: 'string',
            title: 'Live Status'
        },
        session_badges: {
            items: {
                '$ref': '#/components/schemas/WorkshopSessionSelfBadgeGrantPublic'
            },
            type: 'array',
            title: 'Session Badges',
            description: 'Non-revoked badge grants for this user in this session.'
        }
    },
    type: 'object',
    required: ['invited_at', 'joined_at', 'finished_at', 'live_status'],
    title: 'WorkshopParticipantSelfPublic',
    description: 'Caller’s own trainee seat snapshot (participant view only).'
} as const;

export const WorkshopRosterInstructorRowPublicSchema = {
    properties: {
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        email: {
            type: 'string',
            title: 'Email'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        avatar_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Avatar Url'
        },
        role: {
            type: 'string',
            title: 'Role'
        },
        assigned_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Assigned At'
        }
    },
    type: 'object',
    required: ['user_id', 'email', 'full_name', 'role', 'assigned_at'],
    title: 'WorkshopRosterInstructorRowPublic'
} as const;

export const WorkshopRosterParticipantRowPublicSchema = {
    properties: {
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        email: {
            type: 'string',
            title: 'Email'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        avatar_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Avatar Url'
        },
        invited_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Invited At'
        },
        joined_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Joined At'
        },
        finished_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Finished At'
        },
        live_status: {
            type: 'string',
            title: 'Live Status'
        }
    },
    type: 'object',
    required: ['user_id', 'email', 'full_name', 'invited_at', 'joined_at', 'finished_at', 'live_status'],
    title: 'WorkshopRosterParticipantRowPublic'
} as const;

export const WorkshopRosterUserPickerPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/WorkshopRosterUserPickerRowPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'WorkshopRosterUserPickerPublic'
} as const;

export const WorkshopRosterUserPickerRowPublicSchema = {
    properties: {
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        email: {
            type: 'string',
            title: 'Email'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser'
        },
        is_instructor: {
            type: 'boolean',
            title: 'Is Instructor'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active'
        },
        match_score: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Match Score',
            description: 'Best trigram similarity when search q is set; omitted in browse mode.'
        }
    },
    type: 'object',
    required: ['user_id', 'email', 'is_superuser', 'is_instructor', 'is_active'],
    title: 'WorkshopRosterUserPickerRowPublic',
    description: 'One row for instructor roster user picker (browse + fuzzy search).'
} as const;

export const WorkshopSessionCorePublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        current_part_index: {
            type: 'integer',
            title: 'Current Part Index'
        },
        current_part_slug: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Current Part Slug'
        },
        part_generation: {
            type: 'integer',
            title: 'Part Generation'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'status', 'current_part_index', 'current_part_slug', 'part_generation', 'created_at'],
    title: 'WorkshopSessionCorePublic'
} as const;

export const WorkshopSessionCreateSchema = {
    properties: {
        lesson_id: {
            type: 'string',
            format: 'uuid',
            title: 'Lesson Id'
        },
        participant_user_ids: {
            anyOf: [
                {
                    items: {
                        type: 'string',
                        format: 'uuid'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Participant User Ids',
            description: 'Optional trainees to roster immediately after session creation (same transaction as create).'
        }
    },
    type: 'object',
    required: ['lesson_id'],
    title: 'WorkshopSessionCreate'
} as const;

export const WorkshopSessionCreatedPublicSchema = {
    properties: {
        session_id: {
            type: 'string',
            format: 'uuid',
            title: 'Session Id'
        },
        lesson_id: {
            type: 'string',
            format: 'uuid',
            title: 'Lesson Id'
        },
        status: {
            type: 'string',
            title: 'Status'
        }
    },
    type: 'object',
    required: ['session_id', 'lesson_id', 'status'],
    title: 'WorkshopSessionCreatedPublic'
} as const;

export const WorkshopSessionInstructorSeatRoleUpdateSchema = {
    properties: {
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        role: {
            type: 'string',
            maxLength: 32,
            title: 'Role'
        }
    },
    type: 'object',
    required: ['user_id', 'role'],
    title: 'WorkshopSessionInstructorSeatRoleUpdate',
    description: "Update an active instructor seat's role (e.g. co_instructor → lead)."
} as const;

export const WorkshopSessionLeaderboardPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/WorkshopSessionLeaderboardRowPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'WorkshopSessionLeaderboardPublic'
} as const;

export const WorkshopSessionLeaderboardRowPublicSchema = {
    properties: {
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        total_points: {
            type: 'integer',
            minimum: 0,
            title: 'Total Points'
        },
        badge_count: {
            type: 'integer',
            minimum: 0,
            title: 'Badge Count'
        }
    },
    type: 'object',
    required: ['user_id', 'total_points', 'badge_count'],
    title: 'WorkshopSessionLeaderboardRowPublic'
} as const;

export const WorkshopSessionListItemSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        part_generation: {
            type: 'integer',
            title: 'Part Generation'
        },
        lesson_id: {
            type: 'string',
            format: 'uuid',
            title: 'Lesson Id'
        },
        lesson_title: {
            type: 'string',
            title: 'Lesson Title'
        },
        lesson_slug: {
            type: 'string',
            title: 'Lesson Slug'
        },
        my_role: {
            anyOf: [
                {
                    type: 'string',
                    enum: ['participant', 'instructor']
                },
                {
                    type: 'null'
                }
            ],
            title: 'My Role',
            description: 'Trainee/participant vs instructor roster seat; ``null`` when superuser is not seated on this session.'
        },
        blocked_required_prereq_count: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Blocked Required Prereq Count',
            description: 'Roster trainees still missing at least one required prerequisite; only included for instructor/admin visibility.'
        }
    },
    type: 'object',
    required: ['id', 'status', 'part_generation', 'lesson_id', 'lesson_title', 'lesson_slug'],
    title: 'WorkshopSessionListItem',
    description: 'Minimal session row for dashboard lists — no roster, no peer data.'
} as const;

export const WorkshopSessionMemberBatchResultItemSchema = {
    properties: {
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        status: {
            type: 'string',
            enum: ['added', 'already', 'not_found', 'error'],
            title: 'Status'
        },
        detail: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Detail'
        }
    },
    type: 'object',
    required: ['user_id', 'status'],
    title: 'WorkshopSessionMemberBatchResultItem'
} as const;

export const WorkshopSessionMembersBatchBodySchema = {
    properties: {
        user_ids: {
            items: {
                type: 'string',
                format: 'uuid'
            },
            type: 'array',
            maxItems: 100,
            title: 'User Ids',
            description: 'At most 100 user IDs per request; client may chunk larger selections.'
        }
    },
    type: 'object',
    required: ['user_ids'],
    title: 'WorkshopSessionMembersBatchBody',
    description: 'Add multiple participants in one request (instructor-only).'
} as const;

export const WorkshopSessionMembersBatchResponseSchema = {
    properties: {
        results: {
            items: {
                '$ref': '#/components/schemas/WorkshopSessionMemberBatchResultItem'
            },
            type: 'array',
            title: 'Results'
        }
    },
    type: 'object',
    required: ['results'],
    title: 'WorkshopSessionMembersBatchResponse'
} as const;

export const WorkshopSessionPatchSchema = {
    properties: {
        status: {
            anyOf: [
                {
                    type: 'string',
                    enum: ['live', 'paused', 'ended']
                },
                {
                    type: 'null'
                }
            ],
            title: 'Status'
        },
        instructor_seat: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/WorkshopSessionInstructorSeatRoleUpdate'
                },
                {
                    type: 'null'
                }
            ]
        },
        primary_instructor_user_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Primary Instructor User Id'
        },
        remove_instructor_user_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Remove Instructor User Id'
        }
    },
    type: 'object',
    title: 'WorkshopSessionPatch',
    description: 'Session-level PATCH body; at least one field must be present in the request.'
} as const;

export const WorkshopSessionPublicInstructorSchema = {
    properties: {
        view: {
            type: 'string',
            const: 'instructor',
            title: 'View',
            default: 'instructor'
        },
        session: {
            '$ref': '#/components/schemas/WorkshopSessionCorePublic'
        },
        lesson: {
            '$ref': '#/components/schemas/WorkshopLessonSummaryPublic'
        },
        parts: {
            items: {
                '$ref': '#/components/schemas/WorkshopLessonPartBrief'
            },
            type: 'array',
            title: 'Parts'
        },
        participants: {
            items: {
                '$ref': '#/components/schemas/WorkshopRosterParticipantRowPublic'
            },
            type: 'array',
            title: 'Participants'
        },
        instructors: {
            items: {
                '$ref': '#/components/schemas/WorkshopRosterInstructorRowPublic'
            },
            type: 'array',
            title: 'Instructors'
        }
    },
    type: 'object',
    required: ['session', 'lesson', 'parts', 'participants', 'instructors'],
    title: 'WorkshopSessionPublicInstructor',
    description: 'Instructor-visible session detail with roster.'
} as const;

export const WorkshopSessionPublicParticipantSchema = {
    properties: {
        view: {
            type: 'string',
            const: 'participant',
            title: 'View',
            default: 'participant'
        },
        session: {
            '$ref': '#/components/schemas/WorkshopSessionCorePublic'
        },
        lesson: {
            '$ref': '#/components/schemas/WorkshopLessonSummaryPublic'
        },
        parts: {
            items: {
                '$ref': '#/components/schemas/WorkshopLessonPartBrief'
            },
            type: 'array',
            title: 'Parts'
        },
        self: {
            '$ref': '#/components/schemas/WorkshopParticipantSelfPublic'
        }
    },
    type: 'object',
    required: ['session', 'lesson', 'parts', 'self'],
    title: 'WorkshopSessionPublicParticipant',
    description: 'Trainee-visible session detail — lesson + parts + self only (no roster).'
} as const;

export const WorkshopSessionSelfBadgeGrantPublicSchema = {
    properties: {
        badge_id: {
            type: 'string',
            format: 'uuid',
            title: 'Badge Id'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        slug: {
            type: 'string',
            title: 'Slug'
        }
    },
    type: 'object',
    required: ['badge_id', 'title', 'slug'],
    title: 'WorkshopSessionSelfBadgeGrantPublic',
    description: 'Active badge grant for the current user in this session (participant view).'
} as const;

export const WorkshopSessionTimerEventPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        session_id: {
            type: 'string',
            format: 'uuid',
            title: 'Session Id'
        },
        actor_user_id: {
            type: 'string',
            format: 'uuid',
            title: 'Actor User Id'
        },
        action: {
            type: 'string',
            enum: ['start', 'pause', 'resume', 'stop', 'extend'],
            title: 'Action'
        },
        mode: {
            anyOf: [
                {
                    type: 'string',
                    enum: ['countdown', 'countup']
                },
                {
                    type: 'null'
                }
            ],
            title: 'Mode'
        },
        target_seconds: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Target Seconds'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'session_id', 'actor_user_id', 'action'],
    title: 'WorkshopSessionTimerEventPublic'
} as const;

export const WorkshopSessionTimerEventsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/WorkshopSessionTimerEventPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'WorkshopSessionTimerEventsPublic'
} as const;

export const WorkshopSessionTimerExtendSchema = {
    properties: {
        additional_seconds: {
            type: 'integer',
            maximum: 86400,
            minimum: 60,
            title: 'Additional Seconds'
        }
    },
    type: 'object',
    required: ['additional_seconds'],
    title: 'WorkshopSessionTimerExtend'
} as const;

export const WorkshopSessionTimerPublicSchema = {
    properties: {
        session_id: {
            type: 'string',
            format: 'uuid',
            title: 'Session Id'
        },
        status: {
            type: 'string',
            enum: ['inactive', 'running', 'paused'],
            title: 'Status'
        },
        mode: {
            anyOf: [
                {
                    type: 'string',
                    enum: ['countdown', 'countup']
                },
                {
                    type: 'null'
                }
            ],
            title: 'Mode'
        },
        target_seconds: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Target Seconds'
        },
        started_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Started At'
        },
        paused_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Paused At'
        },
        elapsed_seconds: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Elapsed Seconds'
        },
        remaining_seconds: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Remaining Seconds'
        }
    },
    type: 'object',
    required: ['session_id', 'status'],
    title: 'WorkshopSessionTimerPublic'
} as const;

export const WorkshopSessionTimerStartSchema = {
    properties: {
        mode: {
            type: 'string',
            enum: ['countdown', 'countup'],
            title: 'Mode',
            default: 'countdown'
        },
        target_seconds: {
            anyOf: [
                {
                    type: 'integer',
                    maximum: 86400,
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Target Seconds'
        }
    },
    type: 'object',
    title: 'WorkshopSessionTimerStart'
} as const;

export const WorkshopSessionUpsertMemberSchema = {
    properties: {
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        role: {
            type: 'string',
            enum: ['participant', 'instructor'],
            title: 'Role'
        },
        instructor_role: {
            type: 'string',
            maxLength: 32,
            title: 'Instructor Role',
            default: 'co_instructor'
        }
    },
    type: 'object',
    required: ['user_id', 'role'],
    title: 'WorkshopSessionUpsertMember',
    description: 'Assign a user as participant or instructor for one session.'
} as const;

export const WorkshopSessionsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/WorkshopSessionListItem'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'WorkshopSessionsPublic'
} as const;

export const WorkshopWsTicketSchema = {
    properties: {
        ticket: {
            type: 'string',
            title: 'Ticket'
        },
        expires_at: {
            type: 'string',
            format: 'date-time',
            title: 'Expires At'
        }
    },
    type: 'object',
    required: ['ticket', 'expires_at'],
    title: 'WorkshopWsTicket'
} as const;