// This file is auto-generated by @hey-api/openapi-ts

/**
 * Approve a pending GitHub login.
 *
 * Exactly one of ``user_id`` or ``create_user`` must be provided.
 */
export type ApprovePendingRequest = {
    user_id?: (string | null);
    create_user?: boolean;
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

/**
 * Discriminated response from the GitHub bridge endpoint.
 *
 * - ``status="signed_in"`` -> ``access_token`` and ``token_type`` are set,
 * ``pending_id`` is null.
 * - ``status="pending_approval"`` -> ``pending_id`` is set, token fields null.
 */
export type BridgeResponse = {
    status: 'signed_in' | 'pending_approval';
    access_token?: (string | null);
    token_type?: (string | null);
    pending_id?: (string | null);
};

export type status = 'signed_in' | 'pending_approval';

export type GitHubBridgeRequest = {
    bridge_token: string;
};

export type GithubInstallationAccessibleRepositoriesPublic = {
    installation_id: number;
    repository_selection?: (string | null);
    full_names: Array<(string)>;
    count: number;
};

export type GithubInstallationListItemPublic = {
    installation_id: number;
    account_login: string;
    account_type: string;
    repository_selection?: (string | null);
    app_slug?: (string | null);
    suspended: boolean;
    entitled_repositories_count: number;
    entitled_repositories: Array<(string)>;
    installation_settings_url: string;
};

export type GithubInstallationListPublic = {
    data: Array<GithubInstallationListItemPublic>;
    count: number;
    install_url?: (string | null);
};

export type GithubInstallationRefreshBody = {
    include_repositories?: boolean;
};

export type GithubInstallationRefreshPublic = {
    installations_refreshed: number;
    installations_created: number;
    installations_updated: number;
    repositories_refreshed: number;
};

export type GithubInstallationRepositoriesRefreshPublic = {
    installation_id: number;
    repository_selection?: (string | null);
    repositories_total: number;
    added: number;
    removed: number;
    unchanged: number;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type LessonRepoGithubSyncBody = {
    full_name: string;
    installation_id: number;
};

export type LessonRepoGithubSyncPublic = {
    lesson_repo_id: string;
    lessons_synced: number;
    full_name: string;
    health: string;
    default_branch: string;
};

export type LessonRepoListItemPublic = {
    lesson_repo_id: string;
    full_name: string;
    default_branch: string;
    health: string;
    github_installation_id?: (number | null);
    last_synced_at?: (string | null);
    lesson_count: number;
    part_count: number;
    manifest_count: number;
    last_manifest_synced_at?: (string | null);
};

export type LessonRepoListPublic = {
    data: Array<LessonRepoListItemPublic>;
    count: number;
};

export type LessonRepoPreviewLessonPublic = {
    lesson_id: string;
    lesson_slug: string;
    lesson_title: string;
    parts: Array<LessonRepoPreviewPartPublic>;
};

export type LessonRepoPreviewPartPublic = {
    slug: string;
    title: string;
    ordering: number;
    path: string;
};

export type LessonRepoPreviewPublic = {
    lesson_repo_id: string;
    full_name: string;
    default_branch: string;
    health: string;
    lessons: Array<LessonRepoPreviewLessonPublic>;
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type OAuthAccountPublic = {
    id: string;
    user_id: string;
    provider: string;
    provider_account_id: string;
    provider_login?: (string | null);
    avatar_url?: (string | null);
    linked_at?: (string | null);
};

export type PendingGitHubLoginPublic = {
    id: string;
    provider: string;
    provider_account_id: string;
    provider_login?: (string | null);
    email?: (string | null);
    full_name?: (string | null);
    avatar_url?: (string | null);
    first_seen_at?: (string | null);
    last_seen_at?: (string | null);
    attempt_count: number;
};

export type PendingGitHubLoginsPublic = {
    data: Array<PendingGitHubLoginPublic>;
    count: number;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
    is_instructor?: boolean;
};

export type PrivateWorkshopE2ELiveSessionResponse = {
    session_id: string;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    is_instructor?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    is_instructor?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    is_instructor?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type WorkshopBadgeDefinitionCreate = {
    slug: string;
    title: string;
    description?: (string | null);
    points?: number;
};

export type WorkshopBadgeDefinitionPublic = {
    id: string;
    slug: string;
    title: string;
    description?: (string | null);
    points: number;
};

export type WorkshopBadgeDefinitionsPublic = {
    data: Array<WorkshopBadgeDefinitionPublic>;
    count: number;
};

export type WorkshopBadgeGrantRequest = {
    user_id: string;
    badge_id: string;
};

export type WorkshopBadgeRevokeRequest = {
    user_id: string;
    badge_id: string;
    reason?: (string | null);
};

/**
 * Lesson part metadata for workshop session screens (body omitted).
 */
export type WorkshopLessonPartBrief = {
    id: string;
    ordering: number;
    slug: string;
    title: string;
    body_html?: (string | null);
};

/**
 * Session roster completion counts per prerequisite definition (no per-user identity).
 */
export type WorkshopLessonPrerequisiteAggregatePublic = {
    prerequisite: WorkshopLessonPrerequisitePublic;
    /**
     * Active roster trainee seats.
     */
    roster_count: number;
    /**
     * Roster trainees with a completion row for this prerequisite.
     */
    completed_count: number;
};

export type WorkshopLessonPrerequisiteAggregatesPublic = {
    data: Array<WorkshopLessonPrerequisiteAggregatePublic>;
    count: number;
};

export type WorkshopLessonPrerequisiteComplete = {
    user_id?: (string | null);
};

export type WorkshopLessonPrerequisiteCreate = {
    type?: string;
    title: string;
    details?: (string | null);
    url?: (string | null);
    ordering?: number;
    required_flag?: boolean;
};

/**
 * Trainee prerequisite gap for instructor cohort views (scoped to a workshop session roster).
 */
export type WorkshopLessonPrerequisiteGapPublic = {
    user_id: string;
    email: string;
    full_name?: (string | null);
    incomplete_required_prerequisites: Array<WorkshopLessonPrerequisitePublic>;
};

/**
 * Users on the session roster who still owe at least one *required* prerequisite.
 */
export type WorkshopLessonPrerequisiteGapsPublic = {
    data: Array<WorkshopLessonPrerequisiteGapPublic>;
    count: number;
};

export type WorkshopLessonPrerequisiteMyPublic = {
    id: string;
    lesson_id: string;
    type: string;
    title: string;
    details?: (string | null);
    url?: (string | null);
    ordering: number;
    required_flag: boolean;
    is_completed: boolean;
    completed_at?: (string | null);
    source?: (string | null);
};

export type WorkshopLessonPrerequisitePatch = {
    type?: (string | null);
    title?: (string | null);
    details?: (string | null);
    url?: (string | null);
    ordering?: (number | null);
    required_flag?: (boolean | null);
};

export type WorkshopLessonPrerequisitePublic = {
    id: string;
    lesson_id: string;
    type: string;
    title: string;
    details?: (string | null);
    url?: (string | null);
    ordering: number;
    required_flag: boolean;
};

export type WorkshopLessonPrerequisitesMyPublic = {
    data: Array<WorkshopLessonPrerequisiteMyPublic>;
    count: number;
};

export type WorkshopLessonPrerequisitesPublic = {
    data: Array<WorkshopLessonPrerequisitePublic>;
    count: number;
};

export type WorkshopLessonSummaryPublic = {
    id: string;
    title: string;
    slug: string;
    lesson_repo_health?: string;
    lesson_repo_last_synced_at?: (string | null);
    lesson_content_available?: boolean;
    lesson_content_issue?: (string | null);
};

/**
 * Instructor override fields for a participant seat.
 */
export type WorkshopParticipantPatch = {
    live_status?: ('busy' | 'done' | null);
    joined_at?: (string | null);
    finished_at?: (string | null);
};

/**
 * Caller’s own trainee seat snapshot (participant view only).
 */
export type WorkshopParticipantSelfPublic = {
    invited_at: (string | null);
    joined_at: (string | null);
    finished_at: (string | null);
    live_status: string;
};

export type WorkshopRosterInstructorRowPublic = {
    user_id: string;
    email: string;
    full_name: (string | null);
    avatar_url?: (string | null);
    role: string;
    assigned_at: (string | null);
};

export type WorkshopRosterParticipantRowPublic = {
    user_id: string;
    email: string;
    full_name: (string | null);
    avatar_url?: (string | null);
    invited_at: (string | null);
    joined_at: (string | null);
    finished_at: (string | null);
    live_status: string;
};

export type WorkshopSessionCorePublic = {
    id: string;
    status: string;
    current_part_index: number;
    current_part_slug: (string | null);
    part_generation: number;
    created_at: (string | null);
};

export type WorkshopSessionCreate = {
    lesson_id: string;
};

export type WorkshopSessionCreatedPublic = {
    session_id: string;
    lesson_id: string;
    status: string;
};

/**
 * Update an active instructor seat's role (e.g. co_instructor → lead).
 */
export type WorkshopSessionInstructorSeatRoleUpdate = {
    user_id: string;
    role: string;
};

export type WorkshopSessionLeaderboardPublic = {
    data: Array<WorkshopSessionLeaderboardRowPublic>;
    count: number;
};

export type WorkshopSessionLeaderboardRowPublic = {
    user_id: string;
    total_points: number;
    badge_count: number;
};

/**
 * Minimal session row for dashboard lists — no roster, no peer data.
 */
export type WorkshopSessionListItem = {
    id: string;
    status: string;
    part_generation: number;
    lesson_id: string;
    lesson_title: string;
    lesson_slug: string;
    /**
     * Trainee/participant vs instructor roster seat; ``null`` when superuser is not seated on this session.
     */
    my_role?: ('participant' | 'instructor' | null);
    /**
     * Roster trainees still missing at least one required prerequisite; only included for instructor/admin visibility.
     */
    blocked_required_prereq_count?: (number | null);
};

/**
 * Session-level PATCH body; at least one field must be present in the request.
 */
export type WorkshopSessionPatch = {
    status?: ('live' | 'paused' | 'ended' | null);
    instructor_seat?: (WorkshopSessionInstructorSeatRoleUpdate | null);
    primary_instructor_user_id?: (string | null);
    remove_instructor_user_id?: (string | null);
};

/**
 * Instructor-visible session detail with roster.
 */
export type WorkshopSessionPublicInstructor = {
    view?: "instructor";
    session: WorkshopSessionCorePublic;
    lesson: WorkshopLessonSummaryPublic;
    parts: Array<WorkshopLessonPartBrief>;
    participants: Array<WorkshopRosterParticipantRowPublic>;
    instructors: Array<WorkshopRosterInstructorRowPublic>;
};

/**
 * Trainee-visible session detail — lesson + parts + self only (no roster).
 */
export type WorkshopSessionPublicParticipant = {
    view?: "participant";
    session: WorkshopSessionCorePublic;
    lesson: WorkshopLessonSummaryPublic;
    parts: Array<WorkshopLessonPartBrief>;
    self: WorkshopParticipantSelfPublic;
};

export type WorkshopSessionsPublic = {
    data: Array<WorkshopSessionListItem>;
    count: number;
};

export type WorkshopSessionTimerEventPublic = {
    id: string;
    session_id: string;
    actor_user_id: string;
    action: 'start' | 'pause' | 'resume' | 'stop';
    mode?: ('countdown' | 'countup' | null);
    target_seconds?: (number | null);
    created_at?: (string | null);
};

export type action = 'start' | 'pause' | 'resume' | 'stop';

export type WorkshopSessionTimerEventsPublic = {
    data: Array<WorkshopSessionTimerEventPublic>;
    count: number;
};

export type WorkshopSessionTimerPublic = {
    session_id: string;
    status: 'inactive' | 'running' | 'paused';
    mode?: ('countdown' | 'countup' | null);
    target_seconds?: (number | null);
    started_at?: (string | null);
    paused_at?: (string | null);
    elapsed_seconds?: (number | null);
    remaining_seconds?: (number | null);
};

export type status2 = 'inactive' | 'running' | 'paused';

export type WorkshopSessionTimerStart = {
    mode?: 'countdown' | 'countup';
    target_seconds?: (number | null);
};

export type mode = 'countdown' | 'countup';

/**
 * Assign a user as participant or instructor for one session.
 */
export type WorkshopSessionUpsertMember = {
    user_id: string;
    role: 'participant' | 'instructor';
    instructor_role?: string;
};

export type role = 'participant' | 'instructor';

export type WorkshopWsTicket = {
    ticket: string;
    expires_at: string;
};

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type OauthBridgeLoginData = {
    requestBody: GitHubBridgeRequest;
};

export type OauthBridgeLoginResponse = (BridgeResponse);

export type OauthListPendingLoginsData = {
    limit?: number;
    skip?: number;
};

export type OauthListPendingLoginsResponse = (PendingGitHubLoginsPublic);

export type OauthApprovePendingLoginData = {
    pendingId: string;
    requestBody: ApprovePendingRequest;
};

export type OauthApprovePendingLoginResponse = (OAuthAccountPublic);

export type OauthDenyPendingLoginData = {
    pendingId: string;
};

export type OauthDenyPendingLoginResponse = (Message);

export type OauthGetLinkStatusData = {
    userId: string;
};

export type OauthGetLinkStatusResponse = ((OAuthAccountPublic | null));

export type OauthAdminUnlinkGithubData = {
    userId: string;
};

export type OauthAdminUnlinkGithubResponse = (Message);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type PrivateBootstrapE2eWorkshopLiveSessionData = {
    initialStatus?: 'live' | 'scheduled';
    omitParticipantSeat?: boolean;
    participantEmail?: (string | null);
    withIncompleteRequiredPrerequisite?: boolean;
};

export type PrivateBootstrapE2eWorkshopLiveSessionResponse = (PrivateWorkshopE2ELiveSessionResponse);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);

export type WorkshopBadgesReadWorkshopBadgesResponse = (WorkshopBadgeDefinitionsPublic);

export type WorkshopBadgesCreateWorkshopBadgeData = {
    requestBody: WorkshopBadgeDefinitionCreate;
};

export type WorkshopBadgesCreateWorkshopBadgeResponse = (WorkshopBadgeDefinitionPublic);

export type WorkshopBadgesGrantWorkshopBadgeData = {
    requestBody: WorkshopBadgeGrantRequest;
    sessionId: string;
};

export type WorkshopBadgesGrantWorkshopBadgeResponse = (Message);

export type WorkshopBadgesRevokeWorkshopBadgeData = {
    requestBody: WorkshopBadgeRevokeRequest;
    sessionId: string;
};

export type WorkshopBadgesRevokeWorkshopBadgeResponse = (Message);

export type WorkshopBadgesReadWorkshopSessionBadgeLeaderboardData = {
    sessionId: string;
};

export type WorkshopBadgesReadWorkshopSessionBadgeLeaderboardResponse = (WorkshopSessionLeaderboardPublic);

export type WorkshopLessonReposReadLessonReposData = {
    health?: string;
    installationId?: (number | null);
    limit?: number;
    q?: (string | null);
    skip?: number;
};

export type WorkshopLessonReposReadLessonReposResponse = (LessonRepoListPublic);

export type WorkshopLessonReposReadGithubInstallationsData = {
    limit?: number;
    skip?: number;
};

export type WorkshopLessonReposReadGithubInstallationsResponse = (GithubInstallationListPublic);

export type WorkshopLessonReposRefreshGithubInstallationsData = {
    requestBody: GithubInstallationRefreshBody;
};

export type WorkshopLessonReposRefreshGithubInstallationsResponse = (GithubInstallationRefreshPublic);

export type WorkshopLessonReposRefreshGithubInstallationRepositoriesData = {
    installationId: number;
};

export type WorkshopLessonReposRefreshGithubInstallationRepositoriesResponse = (GithubInstallationRepositoriesRefreshPublic);

export type WorkshopLessonReposReadGithubInstallationAccessibleRepositoriesData = {
    installationId: number;
};

export type WorkshopLessonReposReadGithubInstallationAccessibleRepositoriesResponse = (GithubInstallationAccessibleRepositoriesPublic);

export type WorkshopLessonReposReadLessonRepoPreviewData = {
    lessonRepoId: string;
};

export type WorkshopLessonReposReadLessonRepoPreviewResponse = (LessonRepoPreviewPublic);

export type WorkshopLessonReposSyncLessonRepoFromGithubData = {
    requestBody: LessonRepoGithubSyncBody;
};

export type WorkshopLessonReposSyncLessonRepoFromGithubResponse = (LessonRepoGithubSyncPublic);

export type WorkshopLessonsCreateLessonPrerequisiteData = {
    lessonId: string;
    requestBody: WorkshopLessonPrerequisiteCreate;
};

export type WorkshopLessonsCreateLessonPrerequisiteResponse = (WorkshopLessonPrerequisitePublic);

export type WorkshopLessonsReadLessonPrerequisitesData = {
    lessonId: string;
};

export type WorkshopLessonsReadLessonPrerequisitesResponse = (WorkshopLessonPrerequisitesPublic);

export type WorkshopLessonsPatchLessonPrerequisiteData = {
    lessonId: string;
    prerequisiteId: string;
    requestBody: WorkshopLessonPrerequisitePatch;
};

export type WorkshopLessonsPatchLessonPrerequisiteResponse = (WorkshopLessonPrerequisitePublic);

export type WorkshopLessonsDeleteLessonPrerequisiteData = {
    lessonId: string;
    prerequisiteId: string;
};

export type WorkshopLessonsDeleteLessonPrerequisiteResponse = (Message);

export type WorkshopLessonsReadLessonPrerequisiteGapsForSessionRosterData = {
    lessonId: string;
    sessionId: string;
};

export type WorkshopLessonsReadLessonPrerequisiteGapsForSessionRosterResponse = (WorkshopLessonPrerequisiteGapsPublic);

export type WorkshopLessonsReadLessonPrerequisiteAggregatesForSessionRosterData = {
    lessonId: string;
    sessionId: string;
};

export type WorkshopLessonsReadLessonPrerequisiteAggregatesForSessionRosterResponse = (WorkshopLessonPrerequisiteAggregatesPublic);

export type WorkshopLessonsReadMyLessonPrerequisitesData = {
    lessonId: string;
};

export type WorkshopLessonsReadMyLessonPrerequisitesResponse = (WorkshopLessonPrerequisitesMyPublic);

export type WorkshopLessonsCompleteLessonPrerequisiteData = {
    lessonId: string;
    prerequisiteId: string;
    requestBody?: (WorkshopLessonPrerequisiteComplete | null);
};

export type WorkshopLessonsCompleteLessonPrerequisiteResponse = (Message);

export type WorkshopSessionsReadWorkshopSessionsForUserData = {
    limit?: number;
    skip?: number;
};

export type WorkshopSessionsReadWorkshopSessionsForUserResponse = (WorkshopSessionsPublic);

export type WorkshopSessionsCreateWorkshopSessionData = {
    requestBody: WorkshopSessionCreate;
};

export type WorkshopSessionsCreateWorkshopSessionResponse = (WorkshopSessionCreatedPublic);

export type WorkshopSessionsReadWorkshopPartAssetData = {
    partId: string;
    path: string;
    sessionId: string;
    token: string;
};

export type WorkshopSessionsReadWorkshopPartAssetResponse = (unknown);

export type WorkshopSessionsReadWorkshopSessionDetailData = {
    sessionId: string;
};

export type WorkshopSessionsReadWorkshopSessionDetailResponse = ((WorkshopSessionPublicParticipant | WorkshopSessionPublicInstructor));

export type WorkshopSessionsPatchWorkshopSessionData = {
    requestBody: WorkshopSessionPatch;
    sessionId: string;
};

export type WorkshopSessionsPatchWorkshopSessionResponse = (Message);

export type WorkshopSessionsUpsertWorkshopSessionMemberData = {
    requestBody: WorkshopSessionUpsertMember;
    sessionId: string;
};

export type WorkshopSessionsUpsertWorkshopSessionMemberResponse = (Message);

export type WorkshopSessionsRemoveWorkshopSessionParticipantData = {
    sessionId: string;
    userId: string;
};

export type WorkshopSessionsRemoveWorkshopSessionParticipantResponse = (Message);

export type WorkshopSessionsPatchWorkshopSessionParticipantData = {
    requestBody: WorkshopParticipantPatch;
    sessionId: string;
    userId: string;
};

export type WorkshopSessionsPatchWorkshopSessionParticipantResponse = (Message);

export type WorkshopSessionsEnterWorkshopSessionData = {
    sessionId: string;
};

export type WorkshopSessionsEnterWorkshopSessionResponse = (Message);

export type WorkshopSessionsStartWorkshopSessionData = {
    sessionId: string;
};

export type WorkshopSessionsStartWorkshopSessionResponse = (Message);

export type WorkshopSessionsEndWorkshopSessionData = {
    sessionId: string;
};

export type WorkshopSessionsEndWorkshopSessionResponse = (Message);

export type WorkshopSessionsReadWorkshopSessionTimerData = {
    sessionId: string;
};

export type WorkshopSessionsReadWorkshopSessionTimerResponse = (WorkshopSessionTimerPublic);

export type WorkshopSessionsReadWorkshopSessionTimerEventsData = {
    limit?: number;
    sessionId: string;
};

export type WorkshopSessionsReadWorkshopSessionTimerEventsResponse = (WorkshopSessionTimerEventsPublic);

export type WorkshopSessionsStartWorkshopSessionTimerData = {
    requestBody: WorkshopSessionTimerStart;
    sessionId: string;
};

export type WorkshopSessionsStartWorkshopSessionTimerResponse = (WorkshopSessionTimerPublic);

export type WorkshopSessionsPauseWorkshopSessionTimerData = {
    sessionId: string;
};

export type WorkshopSessionsPauseWorkshopSessionTimerResponse = (WorkshopSessionTimerPublic);

export type WorkshopSessionsResumeWorkshopSessionTimerData = {
    sessionId: string;
};

export type WorkshopSessionsResumeWorkshopSessionTimerResponse = (WorkshopSessionTimerPublic);

export type WorkshopSessionsStopWorkshopSessionTimerData = {
    sessionId: string;
};

export type WorkshopSessionsStopWorkshopSessionTimerResponse = (WorkshopSessionTimerPublic);

export type WorkshopSessionsCreateWorkshopWsTicketData = {
    sessionId: string;
};

export type WorkshopSessionsCreateWorkshopWsTicketResponse = (WorkshopWsTicket);