// This file is auto-generated by @hey-api/openapi-ts

/**
 * Approve a pending GitHub login.
 *
 * Exactly one of ``user_id`` or ``create_user`` must be provided.
 */
export type ApprovePendingRequest = {
    user_id?: (string | null);
    create_user?: boolean;
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

/**
 * Discriminated response from the GitHub bridge endpoint.
 *
 * - ``status="signed_in"`` -> ``access_token`` and ``token_type`` are set,
 * ``pending_id`` is null.
 * - ``status="pending_approval"`` -> ``pending_id`` is set, token fields null.
 */
export type BridgeResponse = {
    status: 'signed_in' | 'pending_approval';
    access_token?: (string | null);
    token_type?: (string | null);
    pending_id?: (string | null);
};

export type status = 'signed_in' | 'pending_approval';

export type GitHubBridgeRequest = {
    bridge_token: string;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type OAuthAccountPublic = {
    id: string;
    user_id: string;
    provider: string;
    provider_account_id: string;
    provider_login?: (string | null);
    linked_at?: (string | null);
};

export type PendingGitHubLoginPublic = {
    id: string;
    provider: string;
    provider_account_id: string;
    provider_login?: (string | null);
    email?: (string | null);
    full_name?: (string | null);
    avatar_url?: (string | null);
    first_seen_at?: (string | null);
    last_seen_at?: (string | null);
    attempt_count: number;
};

export type PendingGitHubLoginsPublic = {
    data: Array<PendingGitHubLoginPublic>;
    count: number;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type PrivateWorkshopE2ELiveSessionResponse = {
    session_id: string;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    is_instructor?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    is_instructor?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    is_instructor?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * Lesson part metadata for workshop session screens (body omitted).
 */
export type WorkshopLessonPartBrief = {
    id: string;
    ordering: number;
    slug: string;
    title: string;
};

export type WorkshopLessonSummaryPublic = {
    id: string;
    title: string;
    slug: string;
};

/**
 * Instructor override fields for a participant seat.
 */
export type WorkshopParticipantPatch = {
    live_status?: ('busy' | 'done' | null);
    joined_at?: (string | null);
    finished_at?: (string | null);
};

/**
 * Caller’s own trainee seat snapshot (participant view only).
 */
export type WorkshopParticipantSelfPublic = {
    invited_at: (string | null);
    joined_at: (string | null);
    finished_at: (string | null);
    live_status: string;
};

export type WorkshopRosterInstructorRowPublic = {
    user_id: string;
    email: string;
    full_name: (string | null);
    avatar_url?: (string | null);
    role: string;
    assigned_at: (string | null);
};

export type WorkshopRosterParticipantRowPublic = {
    user_id: string;
    email: string;
    full_name: (string | null);
    avatar_url?: (string | null);
    invited_at: (string | null);
    joined_at: (string | null);
    finished_at: (string | null);
    live_status: string;
};

export type WorkshopSessionCorePublic = {
    id: string;
    status: string;
    current_part_index: number;
    current_part_slug: (string | null);
    part_generation: number;
    created_at: (string | null);
};

/**
 * Update an active instructor seat's role (e.g. co_instructor → lead).
 */
export type WorkshopSessionInstructorSeatRoleUpdate = {
    user_id: string;
    role: string;
};

/**
 * Minimal session row for dashboard lists — no roster, no peer data.
 */
export type WorkshopSessionListItem = {
    id: string;
    status: string;
    part_generation: number;
    lesson_id: string;
    lesson_title: string;
    lesson_slug: string;
    /**
     * Trainee/participant vs instructor roster seat; ``null`` when superuser is not seated on this session.
     */
    my_role?: ('participant' | 'instructor' | null);
};

/**
 * Session-level PATCH body; at least one field must be present in the request.
 */
export type WorkshopSessionPatch = {
    status?: ('live' | 'paused' | 'ended' | null);
    instructor_seat?: (WorkshopSessionInstructorSeatRoleUpdate | null);
    primary_instructor_user_id?: (string | null);
    remove_instructor_user_id?: (string | null);
};

/**
 * Instructor-visible session detail with roster.
 */
export type WorkshopSessionPublicInstructor = {
    view?: "instructor";
    session: WorkshopSessionCorePublic;
    lesson: WorkshopLessonSummaryPublic;
    parts: Array<WorkshopLessonPartBrief>;
    participants: Array<WorkshopRosterParticipantRowPublic>;
    instructors: Array<WorkshopRosterInstructorRowPublic>;
};

/**
 * Trainee-visible session detail — lesson + parts + self only (no roster).
 */
export type WorkshopSessionPublicParticipant = {
    view?: "participant";
    session: WorkshopSessionCorePublic;
    lesson: WorkshopLessonSummaryPublic;
    parts: Array<WorkshopLessonPartBrief>;
    self: WorkshopParticipantSelfPublic;
};

export type WorkshopSessionsPublic = {
    data: Array<WorkshopSessionListItem>;
    count: number;
};

/**
 * Assign a user as participant or instructor for one session.
 */
export type WorkshopSessionUpsertMember = {
    user_id: string;
    role: 'participant' | 'instructor';
    instructor_role?: string;
};

export type role = 'participant' | 'instructor';

export type WorkshopWsTicket = {
    ticket: string;
    expires_at: string;
};

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type OauthBridgeLoginData = {
    requestBody: GitHubBridgeRequest;
};

export type OauthBridgeLoginResponse = (BridgeResponse);

export type OauthListPendingLoginsData = {
    limit?: number;
    skip?: number;
};

export type OauthListPendingLoginsResponse = (PendingGitHubLoginsPublic);

export type OauthApprovePendingLoginData = {
    pendingId: string;
    requestBody: ApprovePendingRequest;
};

export type OauthApprovePendingLoginResponse = (OAuthAccountPublic);

export type OauthDenyPendingLoginData = {
    pendingId: string;
};

export type OauthDenyPendingLoginResponse = (Message);

export type OauthGetLinkStatusData = {
    userId: string;
};

export type OauthGetLinkStatusResponse = ((OAuthAccountPublic | null));

export type OauthAdminUnlinkGithubData = {
    userId: string;
};

export type OauthAdminUnlinkGithubResponse = (Message);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type PrivateBootstrapE2eWorkshopLiveSessionData = {
    initialStatus?: 'live' | 'scheduled';
    omitParticipantSeat?: boolean;
    participantEmail?: (string | null);
};

export type PrivateBootstrapE2eWorkshopLiveSessionResponse = (PrivateWorkshopE2ELiveSessionResponse);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);

export type WorkshopSessionsReadWorkshopSessionsForUserData = {
    limit?: number;
    skip?: number;
};

export type WorkshopSessionsReadWorkshopSessionsForUserResponse = (WorkshopSessionsPublic);

export type WorkshopSessionsReadWorkshopSessionDetailData = {
    sessionId: string;
};

export type WorkshopSessionsReadWorkshopSessionDetailResponse = ((WorkshopSessionPublicParticipant | WorkshopSessionPublicInstructor));

export type WorkshopSessionsPatchWorkshopSessionData = {
    requestBody: WorkshopSessionPatch;
    sessionId: string;
};

export type WorkshopSessionsPatchWorkshopSessionResponse = (Message);

export type WorkshopSessionsUpsertWorkshopSessionMemberData = {
    requestBody: WorkshopSessionUpsertMember;
    sessionId: string;
};

export type WorkshopSessionsUpsertWorkshopSessionMemberResponse = (Message);

export type WorkshopSessionsRemoveWorkshopSessionParticipantData = {
    sessionId: string;
    userId: string;
};

export type WorkshopSessionsRemoveWorkshopSessionParticipantResponse = (Message);

export type WorkshopSessionsPatchWorkshopSessionParticipantData = {
    requestBody: WorkshopParticipantPatch;
    sessionId: string;
    userId: string;
};

export type WorkshopSessionsPatchWorkshopSessionParticipantResponse = (Message);

export type WorkshopSessionsEnterWorkshopSessionData = {
    sessionId: string;
};

export type WorkshopSessionsEnterWorkshopSessionResponse = (Message);

export type WorkshopSessionsStartWorkshopSessionData = {
    sessionId: string;
};

export type WorkshopSessionsStartWorkshopSessionResponse = (Message);

export type WorkshopSessionsEndWorkshopSessionData = {
    sessionId: string;
};

export type WorkshopSessionsEndWorkshopSessionResponse = (Message);

export type WorkshopSessionsCreateWorkshopWsTicketData = {
    sessionId: string;
};

export type WorkshopSessionsCreateWorkshopWsTicketResponse = (WorkshopWsTicket);