/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as LayoutWorkshopsRouteImport } from './routes/_layout/workshops'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutWorkshopNewRouteImport } from './routes/_layout/workshop.new'
import { Route as LayoutWorkshopSessionIdRouteImport } from './routes/_layout/workshop.$sessionId'
import { Route as LayoutDashboardTraineeRouteImport } from './routes/_layout/dashboard/trainee'
import { Route as LayoutDashboardInstructorRouteImport } from './routes/_layout/dashboard/instructor'
import { Route as LayoutDashboardAdminRouteImport } from './routes/_layout/dashboard/admin'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutWorkshopsRoute = LayoutWorkshopsRouteImport.update({
  id: '/workshops',
  path: '/workshops',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutWorkshopNewRoute = LayoutWorkshopNewRouteImport.update({
  id: '/workshop/new',
  path: '/workshop/new',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutWorkshopSessionIdRoute = LayoutWorkshopSessionIdRouteImport.update({
  id: '/workshop/$sessionId',
  path: '/workshop/$sessionId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDashboardTraineeRoute = LayoutDashboardTraineeRouteImport.update({
  id: '/dashboard/trainee',
  path: '/dashboard/trainee',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDashboardInstructorRoute =
  LayoutDashboardInstructorRouteImport.update({
    id: '/dashboard/instructor',
    path: '/dashboard/instructor',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutDashboardAdminRoute = LayoutDashboardAdminRouteImport.update({
  id: '/dashboard/admin',
  path: '/dashboard/admin',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/items': typeof LayoutItemsRoute
  '/settings': typeof LayoutSettingsRoute
  '/workshops': typeof LayoutWorkshopsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard/admin': typeof LayoutDashboardAdminRoute
  '/dashboard/instructor': typeof LayoutDashboardInstructorRoute
  '/dashboard/trainee': typeof LayoutDashboardTraineeRoute
  '/workshop/$sessionId': typeof LayoutWorkshopSessionIdRoute
  '/workshop/new': typeof LayoutWorkshopNewRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/items': typeof LayoutItemsRoute
  '/settings': typeof LayoutSettingsRoute
  '/workshops': typeof LayoutWorkshopsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/': typeof LayoutIndexRoute
  '/dashboard/admin': typeof LayoutDashboardAdminRoute
  '/dashboard/instructor': typeof LayoutDashboardInstructorRoute
  '/dashboard/trainee': typeof LayoutDashboardTraineeRoute
  '/workshop/$sessionId': typeof LayoutWorkshopSessionIdRoute
  '/workshop/new': typeof LayoutWorkshopNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/workshops': typeof LayoutWorkshopsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/dashboard/admin': typeof LayoutDashboardAdminRoute
  '/_layout/dashboard/instructor': typeof LayoutDashboardInstructorRoute
  '/_layout/dashboard/trainee': typeof LayoutDashboardTraineeRoute
  '/_layout/workshop/$sessionId': typeof LayoutWorkshopSessionIdRoute
  '/_layout/workshop/new': typeof LayoutWorkshopNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/items'
    | '/settings'
    | '/workshops'
    | '/auth/callback'
    | '/dashboard/admin'
    | '/dashboard/instructor'
    | '/dashboard/trainee'
    | '/workshop/$sessionId'
    | '/workshop/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/items'
    | '/settings'
    | '/workshops'
    | '/auth/callback'
    | '/'
    | '/dashboard/admin'
    | '/dashboard/instructor'
    | '/dashboard/trainee'
    | '/workshop/$sessionId'
    | '/workshop/new'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/items'
    | '/_layout/settings'
    | '/_layout/workshops'
    | '/auth/callback'
    | '/_layout/'
    | '/_layout/dashboard/admin'
    | '/_layout/dashboard/instructor'
    | '/_layout/dashboard/trainee'
    | '/_layout/workshop/$sessionId'
    | '/_layout/workshop/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/workshops': {
      id: '/_layout/workshops'
      path: '/workshops'
      fullPath: '/workshops'
      preLoaderRoute: typeof LayoutWorkshopsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/workshop/new': {
      id: '/_layout/workshop/new'
      path: '/workshop/new'
      fullPath: '/workshop/new'
      preLoaderRoute: typeof LayoutWorkshopNewRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/workshop/$sessionId': {
      id: '/_layout/workshop/$sessionId'
      path: '/workshop/$sessionId'
      fullPath: '/workshop/$sessionId'
      preLoaderRoute: typeof LayoutWorkshopSessionIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/dashboard/trainee': {
      id: '/_layout/dashboard/trainee'
      path: '/dashboard/trainee'
      fullPath: '/dashboard/trainee'
      preLoaderRoute: typeof LayoutDashboardTraineeRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/dashboard/instructor': {
      id: '/_layout/dashboard/instructor'
      path: '/dashboard/instructor'
      fullPath: '/dashboard/instructor'
      preLoaderRoute: typeof LayoutDashboardInstructorRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/dashboard/admin': {
      id: '/_layout/dashboard/admin'
      path: '/dashboard/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof LayoutDashboardAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutWorkshopsRoute: typeof LayoutWorkshopsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutDashboardAdminRoute: typeof LayoutDashboardAdminRoute
  LayoutDashboardInstructorRoute: typeof LayoutDashboardInstructorRoute
  LayoutDashboardTraineeRoute: typeof LayoutDashboardTraineeRoute
  LayoutWorkshopSessionIdRoute: typeof LayoutWorkshopSessionIdRoute
  LayoutWorkshopNewRoute: typeof LayoutWorkshopNewRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutWorkshopsRoute: LayoutWorkshopsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutDashboardAdminRoute: LayoutDashboardAdminRoute,
  LayoutDashboardInstructorRoute: LayoutDashboardInstructorRoute,
  LayoutDashboardTraineeRoute: LayoutDashboardTraineeRoute,
  LayoutWorkshopSessionIdRoute: LayoutWorkshopSessionIdRoute,
  LayoutWorkshopNewRoute: LayoutWorkshopNewRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
